### ISSUE TITLE
Ошибка во время скачивания

### ISSUE THREAD

**Issue by vistar** [Rast1234/vkd#3]
Спасибо за скрипт!

Запускал в режиме слива стены. Скачалось нормально около 156 постов, но потом вылезла ошибка:

```
Traceback (most recent call last):
  File "./vkd/main.py", line 255, in <module>
    main()
  File "./vkd/main.py", line 195, in main
    process_post(("wall post", x), post, post_parser, json_stuff)
  File "./vkd/main.py", line 133, in process_post
    post_parser(number, data, json_stuff)
  File "***/vkd/PostParser.py", line 99, in __call__
    f(k, raw_data)
  File "***/vkd/PostParser.py", line 144, in attachments
    f_args.append(att[t])
KeyError: u'photos_list'
```

В логе на эту тему:

```
Api.py :   63 #   DEBUG [2014-07-03 16:59:51,186] API call succeeded: https://api.vk.com/method/wall.get?owner_id=***&count=1&offset=155&access_token=***
PostPa :   93 # WARNING [2014-07-03 16:59:51,186] Not implemented: can_delete
PostPa :   94 #    INFO [2014-07-03 16:59:51,187] Saving: attachments, text, comments for 836
main.p :  264 #CRITICAL [2014-07-03 16:59:51,188] Fail
```

Затык на это посте: https://vk.com/wall169967517_2106
Кусок json:

```
"attachments": [
                {
                    "photo": {
                        "access_key": "***", 
                        "src": "http://cs320423.vk.me/v320423517/78/zN4IQi3HsVw.jpg", 
                        "created": 1366212997, 
                        "text": "", 
                        "pid": 300780094, 
                        "height": 266, 
                        "width": 400, 
                        "src_big": "http://cs320423.vk.me/v320423517/79/SW8YXEzM8Gs.jpg", 
                        "src_small": "http://cs320423.vk.me/v320423517/77/K2ygkm9S4PE.jpg", 
                        "aid": -7, 
                        "owner_id": 169967517
                    }, 
                    "type": "photo"
                }, 
                {
                    "type": "photos_list", 
                    "photo_list": [
                        {
                            "access_key": "***", 
                            "src": "http://cs320423.vk.me/v320423517/78/zN4IQi3HsVw.jpg", 
                            "created": 1366212997, 
                            "text": "", 
                            "pid": 300780094, 
                            "height": 266, 
                            "width": 400, 
                            "src_big": "http://cs320423.vk.me/v320423517/79/SW8YXEzM8Gs.jpg", 
                            "src_small": "http://cs320423.vk.me/v320423517/77/K2ygkm9S4PE.jpg", 
                            "aid": -7, 
                            "owner_id": 169967517
                        }
                    ]
                }
            ], 
```

**Comment by fincode** [comment]
Тоже столкнулся с таким, проблема с постами, у которых тип вложений "photos_list", не знаком с питоном, но видимо как-то не корректно атрибуты типа обрабатываются. Падает на строчке 144 f_args.append(att[t]) в PostParser.py. Обошел данную проблему добавив перед этой строчкой:

`if t == 'photos_list':
    continue`

**Comment by Rast1234** [comment]
I abandoned this project and implemented a replacement in C#. It supports more stuff, works much faster and more reliable in general. Still needs some polishing and docs though. See description if you are interested.
