### ISSUE TITLE
Не может преобразовать русские символы в адресе

### ISSUE THREAD

**Issue by vistar** [Rast1234/vkd#4]
Предыдущий пос с ошибкой решил пропустить пока, но далее:

```
Traceback (most recent call last):
  File "./vkd/main.py", line 255, in <module>
    main()
  File "./vkd/main.py", line 195, in main
    process_post(("wall post", x), post, post_parser, json_stuff)
  File "./vkd/main.py", line 133, in process_post
    post_parser(number, data, json_stuff)
  File "***/vkd/PostParser.py", line 99, in __call__
    f(k, raw_data)
  File "***/vkd/PostParser.py", line 149, in attachments
    f(a)
  File "***/vkd/PostParser.py", line 227, in dl_link
    out_file.write(url)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 25-28: ordinal not in range(128)
```

```
"url": "http://slovari.yandex.ru/няша/значение/", 
```

Система - linux.

**Comment by Rast1234** [comment]
I abandoned this project and implemented a replacement in C#. It supports more stuff, works much faster and more reliable in general. Still needs some polishing and docs though. See description if you are interested.
