### ISSUE TITLE
Не скачивается стена

### ISSUE THREAD

**Issue by AquaGen** [Rast1234/vkd#6]
Нужно скачать стену, на которой 13 тысяч записей. Несколько раз пробовал. Во-первых, почему-то не всегда качается. Т.е. что-то скачалось, написано 100%, а следующее начинает качаться только через 5 минут.
Во-вторых уже не один раз такая ошибка после 10 тысяч. Что это значит и что мне делать

Downloading: .-68623367\10607\w2abol-xvVk.jpg (106 kb)
Traceback (most recent call last):
  File "C:\Users\╚т\Downloads\vkd-master\vkd-master\main.py", line 255, in <modu
le>
    main()
  File "C:\Users\╚т\Downloads\vkd-master\vkd-master\main.py", line 195, in main
    process_post(("wall post", x), post, post_parser, json_stuff)
  File "C:\Users\╚т\Downloads\vkd-master\vkd-master\main.py", line 133, in proce
ss_post
    post_parser(number, data, json_stuff)
  File "C:\Users\╚т\Downloads\vkd-master\vkd-master\PostParser.py", line 103, in
 **call**
    self.post_directory,
  File "C:\Users\╚т\Downloads\vkd-master\vkd-master\Download.py", line 15, in do
wnload
    u = urllib2.urlopen(url)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 469, in error
    result = self._call_chain(_args)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(_args)
  File "C:\Python27\lib\urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 475, in error
    return self._call_chain(_args)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(_args)
  File "C:\Python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

vkd-master\vkd-master>

**Comment by AquaGen** [comment]
уже несколько раз удалял папку и начинал скачивать сначала, все равно останавливается закачка

**Comment by Rast1234** [comment]
При скачивании чего-то вебсервер возвращает ответ с кодом 404 - это значит,
такого файла больше нет. Это не ошибка vkd, просто реально что-то удалено,
а ссылка осталась. Что именно не удается скачать - см. в логах. Можно это
обойти, дождавшись падения (например, упало на 1000-м посте) и потом начав
скачивать со следующего поста (параметр wall_offset=1001)

**Comment by AquaGen** [comment]
логи это report.log? там так
...
main.p :  264 #CRITICAL [2015-06-23 19:56:55,736] Fail
main.p :  254 #    INFO [2015-06-23 20:15:33,177] Start
main.p :  264 #CRITICAL [2015-06-23 20:15:33,206] Fail

> wall_offset=1001
там ставить номер поста как он в папках сохраняется? типа 13352. или по порядку вручную отсчитывать от первого свеху поста номер

**Comment by Rast1234** [comment]
номер нужно ставить по порядку, 13352 - это идентификатор поста, а не номер. можно просто посчитать количество скачавшихся постов (это ведь количество папок).

в том посте, где ошибка, может быть что-то еще. по-хорошему, надо бы поправить код, чтобы он не падал с ошибкой, а скачивал что сможет. но мне влом :)

ошибка 404 это стандартная ошибка для любого сайта. кто-то мог, например, фотографию удалить, и теперь сервера вконтакта по ссылке на эту фотографию будут отвечать ошибкой 404. смысла писать об этом в поддержку нет.

**Comment by AquaGen** [comment]
>смысла писать об этом в поддержку нет.

а как же тогда исправить эту проблему? чтобы при этой ошибке скачивание не останавливалось, а скачивались следующие файлы

**Comment by AquaGen** [comment]
оставил скачиваться, а там вместо скачивания еще какая-то ошибка вылезла.
когда открыт браузер опера почему-то не качается (запустил и ничего не происходит), а когда отхожу - ошибки какие-то :(

Downloading: .\-68623367\7720\PnF_JG8en_0.jpg (45 kb)
Traceback (most recent call last):
  File "C:\Users\╚т\Downloads\vkd-master\vkd-master\main.py", line 255, in <modu
le>
    main()
  File "C:\Users\╚т\Downloads\vkd-master\vkd-master\main.py", line 195, in main
    process_post(("wall post", x), post, post_parser, json_stuff)
  File "C:\Users\╚т\Downloads\vkd-master\vkd-master\main.py", line 133, in proce
ss_post
    post_parser(number, data, json_stuff)
  File "C:\Users\╚т\Downloads\vkd-master\vkd-master\PostParser.py", line 99, in
__call__
    f(k, raw_data)
  File "C:\Users\╚т\Downloads\vkd-master\vkd-master\PostParser.py", line 167, in
 comments
    ], self.args)
  File "C:\Users\╚т\Downloads\vkd-master\vkd-master\Api.py", line 46, in call_ap
i
    json_stuff = urllib2.urlopen(url).read()
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:5
90)>

**Comment by Rast1234** [comment]
Странная ошибка. Не знаю, что это, особенно с учетом того, что что-то у вас скачивается в начале. Если бы вообще ничего не скачивалось, тогда другое дело..
Насчет Opera не знаю, не пользуюсь ей.

**Comment by Rast1234** [comment]
вообще, конечно, плохо, что при любой сетевой или серверной ошибке программа падает замертво. я было взялся писать обновленную версию с более вменяемой обработкой ошибок, но забросил. думаю, завтра напишу новую. поможете с тестированием? ;)

**Comment by AquaGen** [comment]
>поможете с тестированием? ;)
хорошо. еще бы возможность скачивания личных сообщений...

**Comment by Rast1234** [comment]
попробую сделать, если вконтакт умеет отдавать сообщения. раньше не умел.

**Comment by Rast1234** [comment]
I abandoned this project and implemented a replacement in C#. It supports more stuff, works much faster and more reliable in general. Still needs some polishing and docs though. See description if you are interested.
